from enum import Enum


class Products(Enum):

    ANDROID_QUICK_START_GUIDE = 1
    FUNCTIONAL_PROGRAMMING_IN_JS = 2
    HTML5_FORMS = 3
    HTML5_WEBAPP_DEVELOPMENT = 4
    JS_DATA_STRUCTURES_AND_ALGORITHM = 5

class States(Enum):
    ANDHRA_PRADESH = 1
    ARUNACHAL_PRADESH = 2
    ASSAM = 3
    BIHAR = 4
    CHHATISGARH = 5
    GOA = 6
    GUJARAT = 7
    HARYANA = 8
    HIMACHAL_PRADESH = 9
    JAMMU_AND_KASHMIR = 10
    JHARKAND = 11
    KARNATAKA = 12
    KERALA = 13
    MADHYA_PRADESH = 14
    MAHARASHTRA = 15
    MANIPUR = 16
    MEGHALAYA = 17
    MIZORAM = 18
    NAGALAND = 19
    ORISSA = 20
    PUNJAB = 21
    RAJASTHAN = 22
    SIKKIM = 23
    TAMIL_NADU = 24
    TELANGANA = 25
    TRIPURA = 26
    UTTARAKHAND = 27
    UTTAR_PRADESH = 28
    WEST_BENGAL = 29
    ANDAMAN_AND_NICOBAR_ISLANDS = 30
    CHANDIGARH = 31
    DADAR_AND_NAGAR_HAVELI = 32
    DAMAN_AND_DIHU = 33
    DELHI = 34
    LAKSHADEEP = 35
    PONDICHERRY = 36
